name: laser_tech_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  #################################################
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.16
  hive_flutter: ^1.1.0
  connectivity_plus: ^3.0.2
  freezed_annotation: ^2.2.0
  flutter_screenutil: ^5.6.0
  get: ^4.6.5
  flutter_localization:
  dartz: ^0.10.1
  http: ^0.13.5
  qr_code_scanner: ^1.0.1
  video_player: ^2.5.1
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.3
  chewie: ^1.4.0
  dio: ^4.0.6
  # qr_flutter: ^4.0.0
  image_picker: ^0.8.6+4
  carousel_slider: ^4.2.1
  flutter_svg: ^0.22.0
  file_picker: ^4.6.1
  path_provider: ^2.0.13
  data_table_2: ^2.4.1

 

 
  #################################################
dev_dependencies:
  flutter_test:
    sdk: flutter
  ##################################################
  flutter_lints: ^2.0.0
  intl: ^0.17.0-nullsafety.2
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  ##################################################
flutter:
  generate: true 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/Door_images/
    - assets/videos/


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
